### ISSUE TITLE
 Hello, excuse you, I want to ask which folder the MyScripts folder is, and I didn’t find it in my files

### ISSUE THREAD

**Issue by xiaojia998** [duritskiy/easyeda-MyExtensions#1]
Hello, excuse you, I want to ask which folder the MyScripts folder is, and I didn’t find it in my files

**Comment by duritskiy** [comment]
I have changed the description. It seems to me that it should be clearer now. If you still do not understand, please ask, I will answer.

**Comment by xiaojia998** [comment]
Thank you very much for your sharing and help, I have successfully completed the plug-in installation
